config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :chirps

  root to: "chirps#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chirp.rb
class Chirp < ApplicationRecord
  validates :text, presence: true, length: { maximum: 140 }
  validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action do
    @author = cookies[:author] ||= Faker::Internet.username
  end

  rescue_from ActiveRecord::StatementInvalid do |e|
    if e.cause.is_a?(PG::ReadOnlySqlTransaction)
      r = ENV["PRIMARY_REGION"]
      response.headers["fly-replay"] = "region=#{r}"
      Rails.logger.info "Replaying request in #{r}"
      render plain: "retry in region #{r}", status: 409
    else
      raise e
    end
  end
end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  def index
    @chirps = Chirp.order(created_at: :desc)
  end

  def create
    @chirp = Chirp.new(params.require(:chirp).permit(:text).merge({
      author: @author,
    }))

    @chirp.save
    @chirps = Chirp.order(created_at: :desc)
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chirps/index.html.erb
<h1>Chirps!</h1>
<p>Served from: <strong><%= ENV["FLY_REGION"] %></strong></p>
<%= form_with scope: :chirp, url: chirps_path, local: true do |form| %>
  <p>
    <%= form.text_area :text, placeholder: "what's happening?", style: "width: 100%" %>
    <em>Sincerely, <%= @author %></em>
  </p>
 
  <p>
    <%= form.submit "CHIRP" %>
  </p>
<% end %>


<% @chirps.each do |chirp| %>
  <div style="background-color: #80CBC4; padding: 6px;">
    <p style="font-size: 150%; margin: 0">
      <%= chirp.text %>
    </p>
    <em>
      Sincerely, <%= chirp.author %>
    </em>
    <br />
    <%= time_ago_in_words(chirp.created_at) %> ago
  </div>
  <hr />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body style="background-color: #B2DFDB">
    <div style="max-width: 300px; margin: 0 auto;">
      <%= yield %>
    </div>
  </body>
</html>